[default]
description = "Default permissions for the plugin"
permissions = ["allow-create", "allow-list", "allow-get", "allow-start", "allow-cancel", "allow-pause", "allow-resume", "allow-registerListener"]
